spring:
  application:
    name: FilmForum

  datasource:
    hikari:
      minimum-idle: 3
      maximum-pool-size: 10

    # mysql服务地址 格式：jdbc:mysql://{mysql服务所在IP地址}:{mysql服务所在端口}/{数据库名称}?{一些参数}
    url: jdbc:mysql://127.0.0.1:3306/123456?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf-8
    # 使用的用户名
    username: root
    # 用户名对应的密码
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  session:
    jdbc:
      initialize-schema: always
    timeout: 14400


server:
  port: 8082
  forward-headers-strategy: native
  servlet:
    session:
      cookie:
        same-site: none
        secure: true

oauth2:
  qq:
    # QQ登录所需信息，此处仅做示例
    appId: appId
    appKey: appKey
    redirectUri: redirectUri
    successRedirect: successRedirect
    failureRedirect: failureRedirect